package com.priyanshu.RecoverAi.enums;

public enum AuditEventType {

    PAYMENT_FAILED,
    PAYMENT_CAPTURED,

    RECOVERY_CASE_CREATED,
    PRIORITY_ASSIGNED,
    ACTION_RECOMMENDED,

    RECOVERY_MARKED_SUCCESS,
    RECOVERY_STOPPED,

    DUPLICATE_WEBHOOK_IGNORED,
    WEBHOOK_RECEIVED,
    WEBHOOK_PROCESSED,

    ML_PREDICTION_GENERATED,

    POLICY_DECISION_GENERATED,

    AI_AGENT_ANALYSIS_GENERATED,

    RECOVERY_ACTION_STARTED,
    RECOVERY_ACTION_SUCCEEDED,
    RECOVERY_ACTION_FAILED,
    RECOVERY_ACTION_SKIPPED,
    RECOVERY_ACTION_REQUIRES_APPROVAL,

    RECOVERY_APPROVED,
    RECOVERY_REJECTED,

}
